server:
  port: 24903

spring:
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  profiles:
    active: TEST
  application:
    name: demo-test-es
  elasticsearch:
    uris: 127.0.0.1:9200
    username: elastic
    password: k4s9kJmT1ErmsVLRGE5K
    socket-timeout: 3000

my:
  cron:
    value: 0/1 * * * * ?